# name: docker-compose

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Build Nginx Docker image
#       run: |
#         docker build -t mynginx .
#       working-directory: dockerized/nginx
      
#     - name: Set up environment variables
#       run: |
#         echo "DOCKER_USERNAME=$(grep DOCKER_USERNAME .env | cut -d '=' -f2)" >> $GITHUB_ENV
#         echo "DOCKER_PASSWORD=$(grep DOCKER_PASSWORD .env | cut -d '=' -f2)" >> $GITHUB_ENV
#         echo "SSH_HOST=$(grep SSH_HOST .env | cut -d '=' -f2)" >> $GITHUB_ENV
#         echo "SSH_USERNAME=$(grep SSH_USERNAME .env | cut -d '=' -f2)" >> $GITHUB_ENV
#         echo "SSH_PASSWORD=$(grep SSH_PASSWORD .env | cut -d '=' -f2)" >> $GITHUB_ENV

#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         registry: docker.io
#         username: ${{ env.DOCKER_USERNAME }}
#         password: ${{ env.DOCKER_PASSWORD }}
#         token: ${{ env.ACCESS_TOKEN }}


#     - name: Push Nginx Docker image
#       run: |
#         docker tag mynginx ${{ env.DOCKER_USERNAME }}/mynginx:latest
#         docker push ${{ env.DOCKER_USERNAME }}/mynginx:latest
